In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 서울시 지하철 호선별 역별 유_무임 승하차 인원 정보.csv

In [16]:
file_path1 = 'data/raw/서울시 지하철 호선별 역별 유_무임 승하차 인원 정보.csv'
df1 = pd.read_csv(file_path1, encoding='cp949')
df1.head()

      사용월  호선명          지하철역  유임승차인원  무임승차인원  유임하차인원  무임하차인원      작업일자
0  202602  1호선           제기동  196028  247387  190982  269572  20260303
1  202602  1호선  청량리(서울시립대입구)  365106  273195  361825  277193  20260303
2  202602  1호선           동묘앞  141416  143029  148703  144988  20260303
3  202602  1호선            시청  574229   91962  584626   90776  20260303
4  202602  1호선            종각  868096  133930  844844  125034  20260303

In [17]:
df1.shape

(81546, 8)

In [18]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81546 entries, 0 to 81545
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용월     81546 non-null  int64
 1   호선명     81546 non-null  object
 2   지하철역    81546 non-null  object
 3   유임승차인원  81546 non-null  int64
 4   무임승차인원  81546 non-null  int64
 5   유임하차인원  81546 non-null  int64
 6   무임하차인원  81546 non-null  int64
 7   작업일자    81546 non-null  int64
dtypes: int64(6), object(2)
memory usage: 5.0+ MB

In [19]:
df1['호선명'].unique()

array(['1호선', '2호선', '3호선', '4호선', '5호선', '6호선', '7호선', '8호선', '9호선',
       '9호선2~3단계', '경강선', '경부선', '경원선', '경의선', '경인선', '경춘선', '공항철도 1호선',
       '과천선', '분당선', '서해선', '수인선', '신림선', '안산선', '우이신설선', '일산선', '장항선',
       '중앙선', '9호선2단계'], dtype=object)

In [20]:
df1['지하철역'].nunique()

600

# 서울시 지하철 역사 노약자 장애인 편의시설 현황.csv

In [22]:
file_path2 = 'data/raw/서울시 지하철 역사 노약자 장애인 편의시설 현황.csv'
df2 = pd.read_csv(file_path2, encoding='cp949')
df2.head()

    호선       역명  엘리베이터(E/V)  에스컬레이터(E/S)  휠체어리프트(W/L)  수평자동보도(M/W)
0  1호선   서울역(1)           4            5            0            0
1  1호선    시청(1)           3            3            0            0
2  1호선       종각           4            2            0            0
3  1호선  종로3가(1)           3            4            0            0
4  1호선     종로5가           3            0            0            0

In [24]:
df2.shape

(274, 6)

In [25]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274 entries, 0 to 273
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   호선           274 non-null    object
 1   역명           274 non-null    object
 2   엘리베이터(E/V)   274 non-null    int64
 3   에스컬레이터(E/S)  274 non-null    int64
 4   휠체어리프트(W/L)  274 non-null    int64
 5   수평자동보도(M/W)  274 non-null    int64
dtypes: int64(4), object(2)
memory usage: 13.0+ KB

# 서울교통공사_엘리베이터 설치현황_20260211.csv

In [26]:
file_path3 = 'data/raw/서울교통공사_엘리베이터 설치현황_20260211.csv'
df3 = pd.read_csv(file_path3, encoding='cp949')
df3.head()

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

,연번,호선,역 명,관리번호(호기),(근접)출입구번호,시작층(상세위치),시작층(지상_지하),시작층(운행역층),종료층(지상_지하),종료층(운행역층),정원(인원수),정원(중량),승강기 일련번호,데이터 기준일자
0,1,1호선,서울역(1),내부#1,내부,시청 방면5-1,지하,2,지하,1,11,750,0074-205,2026-02-11
1,2,1호선,서울역(1),외부#1,2번출구,2번 출구 측,지하,1,지상,1,13,900,0104-656,2026-02-11
2,3,1호선,서울역(1),외부#2,4번출구,4번 출구 측,지하,1,지상,1,15,1000,0105-867,2026-02-11
3,4,1호선,서울역(1),외부#3,3번출구,3번 출구 측,지하,1,지상,1,15,1000,0073-979,2026-02-11
4,5,1호선,시청(1),내부#1,내부,종각 방면3-2,지하,2,지하,1,15,1000,0002-888,2026-02-11

In [27]:
df3.shape

(867, 14)

In [28]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 867 entries, 0 to 866
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   연번          867 non-null    int64
 1   호선          867 non-null    object
 2   역  명        867 non-null    object
 3   관리번호(호기)    867 non-null    object
 4   (근접)출입구번호   867 non-null    object
 5   시작층(상세위치)   867 non-null    object
 6   시작층(지상_지하)  867 non-null    object
 7   시작층(운행역층)   867 non-null    object
 8   종료층(지상_지하)  867 non-null    object
 9   종료층(운행역층)   867 non-null    object
 10  정원(인원수)     867 non-null    int64
 11  정원(중량)      867 non-null    int64
 12  승강기 일련번호    867 non-null    object
 13  데이터 기준일자    867 non-null    object
dtypes: int64(3), object(11)
memory usage: 95.0+ KB