In [139]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [140]:
s2023_df = pd.read_csv('../../data/raw/서울시 지하철 호선별 역별 유_무임 승하차 인원 정보_2023.csv')

In [141]:
s2023_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7386 entries, 0 to 7385
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용월     7386 non-null   int64
 1   호선명     7386 non-null   object
 2   지하철역    7386 non-null   object
 3   유임승차인원  7386 non-null   int64
 4   무임승차인원  7386 non-null   int64
 5   유임하차인원  7386 non-null   int64
 6   무임하차인원  7386 non-null   int64
 7   작업일자    7386 non-null   int64
dtypes: int64(6), object(2)
memory usage: 461.8+ KB

In [142]:
print(s2023_df.isnull().sum())
print()
print(f'중복행: {s2023_df.duplicated().sum()}')

사용월       0
호선명       0
지하철역      0
유임승차인원    0
무임승차인원    0
유임하차인원    0
무임하차인원    0
작업일자      0
dtype: int64

중복행: 0

In [143]:
s2023_df[s2023_df.duplicated(keep=False)]

Empty DataFrame
Columns: [사용월, 호선명, 지하철역, 유임승차인원, 무임승차인원, 유임하차인원, 무임하차인원, 작업일자]
Index: []

In [144]:
s2024_df = pd.read_csv('../../data/raw/서울시 지하철 호선별 역별 유_무임 승하차 인원 정보_2024.csv')

In [145]:
s2024_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8068 entries, 0 to 8067
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용월     8068 non-null   int64
 1   호선명     8068 non-null   object
 2   지하철역    8068 non-null   object
 3   유임승차인원  8068 non-null   int64
 4   무임승차인원  8068 non-null   int64
 5   유임하차인원  8068 non-null   int64
 6   무임하차인원  8068 non-null   int64
 7   작업일자    8068 non-null   int64
dtypes: int64(6), object(2)
memory usage: 504.4+ KB

In [146]:
print(s2024_df.isnull().sum())
print()
print(f'중복행: {s2024_df.duplicated().sum()}')

사용월       0
호선명       0
지하철역      0
유임승차인원    0
무임승차인원    0
유임하차인원    0
무임하차인원    0
작업일자      0
dtype: int64

중복행: 620

In [147]:
s2024_df[s2024_df.duplicated(keep=False)]

         사용월  호선명          지하철역  유임승차인원  무임승차인원  유임하차인원  무임하차인원      작업일자
6209  202402  1호선           동묘앞  144619  142038  155082  144687  20240303
6210  202402  1호선  청량리(서울시립대입구)  350437  266447  340983  268232  20240303
6211  202402  1호선           제기동  215365  254164  207846  271449  20240303
6212  202402  1호선           신설동  257411  110367  248804  107289  20240303
6213  202402  1호선           동대문  224713  113712  225306  113175  20240303
...      ...  ...           ...     ...     ...     ...     ...       ...
7444  202402  중앙선            상봉  119677   37842  117749   36705  20240303
7445  202402  중앙선            중랑  101785   45693   97927   44969  20240303
7446  202402  중앙선            회기  540835  111210  519096  109273  20240303
7447  202402  중앙선            지평     680     837     737     836  20240303
7448  202402  중앙선            용문   27662   26472   28725   26435  20240303

[1240 rows x 8 columns]

In [148]:
s2024_df[s2024_df['사용월'] == 202402].duplicated().sum()

np.int64(620)

In [149]:
s2024_df = s2024_df.drop_duplicates()

print(f"중복 제거 후 전체 행 개수: {len(s2024_df)}")
print(f"남은 중복 행 개수: {s2024_df.duplicated().sum()}")

중복 제거 후 전체 행 개수: 7448
남은 중복 행 개수: 0

In [150]:
s2025_df = pd.read_csv('../../data/raw/서울시 지하철 호선별 역별 유_무임 승하차 인원 정보_2025.csv')

In [151]:
s2025_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7456 entries, 0 to 7455
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용월     7456 non-null   int64
 1   호선명     7456 non-null   object
 2   지하철역    7456 non-null   object
 3   유임승차인원  7456 non-null   int64
 4   무임승차인원  7456 non-null   int64
 5   유임하차인원  7456 non-null   int64
 6   무임하차인원  7456 non-null   int64
 7   작업일자    7456 non-null   int64
dtypes: int64(6), object(2)
memory usage: 466.1+ KB

In [152]:
print(s2025_df.isnull().sum())
print()
print(f'중복행: {s2025_df.duplicated().sum()}')

사용월       0
호선명       0
지하철역      0
유임승차인원    0
무임승차인원    0
유임하차인원    0
무임하차인원    0
작업일자      0
dtype: int64

중복행: 0

In [153]:
subway_user_df = pd.concat([s2023_df,s2024_df,s2025_df], ignore_index=True)
subway_user_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22290 entries, 0 to 22289
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용월     22290 non-null  int64
 1   호선명     22290 non-null  object
 2   지하철역    22290 non-null  object
 3   유임승차인원  22290 non-null  int64
 4   무임승차인원  22290 non-null  int64
 5   유임하차인원  22290 non-null  int64
 6   무임하차인원  22290 non-null  int64
 7   작업일자    22290 non-null  int64
dtypes: int64(6), object(2)
memory usage: 1.4+ MB

In [154]:
line_list = [f'{i}호선' for i in range(1, 10)]
line_1_9_df = subway_user_df[subway_user_df['호선명'].isin(line_list)]

In [155]:
print(line_1_9_df['호선명'].unique())

['1호선' '2호선' '3호선' '4호선' '5호선' '6호선' '7호선' '8호선' '9호선']

In [156]:
# 상봉역 통일
line_1_9_df['지하철역'] = line_1_9_df['지하철역'].str.replace('상봉(시외버스터미널)', '상봉', regex=False)

/var/folders/rx/ylxcpmnn5hz6xwbkxhnfnxfm0000gn/T/ipykernel_7953/3374613786.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  line_1_9_df['지하철역'] = line_1_9_df['지하철역'].str.replace('상봉(시외버스터미널)', '상봉', regex=False)

In [157]:
# 각 역의 총 승하차인원, 무임승하차인원
line_1_9_df['총승차인원'] = line_1_9_df['유임승차인원'] + line_1_9_df['무임승차인원']
line_1_9_df['총하차인원'] = line_1_9_df['유임하차인원'] + line_1_9_df['무임하차인원']

mean_df = line_1_9_df.groupby(['호선명', '지하철역'])[['총승차인원', '무임승차인원', '총하차인원', '무임하차인원']].mean().round(0).reset_index()

print(mean_df)

     호선명       지하철역      총승차인원    무임승차인원      총하차인원    무임하차인원
0    1호선        동대문   363678.0  125523.0   356249.0  125026.0
1    1호선        동묘앞   308894.0  157888.0   316892.0  159511.0
2    1호선        서울역  1794960.0  229681.0  1701907.0  217787.0
3    1호선         시청   762366.0  107582.0   766076.0  105764.0
4    1호선        신설동   411861.0  120797.0   397175.0  117111.0
..   ...        ...        ...       ...        ...       ...
308  9호선       양천향교   289659.0   49752.0   294136.0   49308.0
309  9호선        여의도   840341.0   56004.0   804546.0   51738.0
310  9호선         염창   514529.0   80870.0   492565.0   78794.0
311  9호선         증미   219073.0   38743.0   210572.0   38823.0
312  9호선  흑석(중앙대입구)   274749.0   60214.0   279485.0   60496.0

[313 rows x 6 columns]

/var/folders/rx/ylxcpmnn5hz6xwbkxhnfnxfm0000gn/T/ipykernel_7953/39438560.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  line_1_9_df['총승차인원'] = line_1_9_df['유임승차인원'] + line_1_9_df['무임승차인원']
/var/folders/rx/ylxcpmnn5hz6xwbkxhnfnxfm0000gn/T/ipykernel_7953/39438560.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  line_1_9_df['총하차인원'] = line_1_9_df['유임하차인원'] + line_1_9_df['무임하차인원']

In [158]:
# 1~9호선에서 이제 서울에만 해당되는 데이터로 추린다.
non_seoul = [
    # 5호선 (하남)
    '미사', '하남검단산', '하남시청(덕풍?신장)', '하남풍산',
    # 7호선 (경기/인천)
    '광명사거리', '굴포천', '까치울', '부천시청', '부평구청',
    '삼산체육관', '상동', '신중동', '춘의', '철산',
    # 8호선 (성남)
    '남위례', '남한산성입구(성남법원.검찰청)', '단대오거리',
    '모란', '복정', '산성', '수진', '신흥',
]
seoul_mean_df = mean_df[~mean_df['지하철역'].isin(non_seoul)]

In [159]:
print(f'제외 전: {len(mean_df)}개역 → 제외 후: {len(seoul_mean_df)}개역')

제외 전: 313개역 → 제외 후: 291개역

In [160]:
# 무임승하차 비중 계산
seoul_mean_df['전체승하차'] = seoul_mean_df['총승차인원'] + seoul_mean_df['총하차인원']
seoul_mean_df['무임승하차'] = seoul_mean_df['무임승차인원'] + seoul_mean_df['무임하차인원']
seoul_mean_df['무임승하차비중'] = (seoul_mean_df['무임승하차'] / seoul_mean_df['전체승하차'] * 100).round(2)

print(seoul_mean_df[['호선명', '지하철역', '전체승하차', '무임승하차', '무임승하차비중']])

     호선명       지하철역      전체승하차     무임승하차  무임승하차비중
0    1호선        동대문   719927.0  250549.0    34.80
1    1호선        동묘앞   625786.0  317399.0    50.72
2    1호선        서울역  3496867.0  447468.0    12.80
3    1호선         시청  1528442.0  213346.0    13.96
4    1호선        신설동   809036.0  237908.0    29.41
..   ...        ...        ...       ...      ...
308  9호선       양천향교   583795.0   99060.0    16.97
309  9호선        여의도  1644887.0  107742.0     6.55
310  9호선         염창  1007094.0  159664.0    15.85
311  9호선         증미   429645.0   77566.0    18.05
312  9호선  흑석(중앙대입구)   554234.0  120710.0    21.78

[291 rows x 5 columns]

/var/folders/rx/ylxcpmnn5hz6xwbkxhnfnxfm0000gn/T/ipykernel_7953/2242440901.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_mean_df['전체승하차'] = seoul_mean_df['총승차인원'] + seoul_mean_df['총하차인원']
/var/folders/rx/ylxcpmnn5hz6xwbkxhnfnxfm0000gn/T/ipykernel_7953/2242440901.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_mean_df['무임승하차'] = seoul_mean_df['무임승차인원'] + seoul_mean_df['무임하차인원']
/var/folders/rx/ylxcpmnn5hz6xwbkxhnfnxfm0000gn/T/ipykernel_7953/2242440901.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_mean_df['무임승하차비중'] = (seoul_mean_df['무임승하차'] / seoul_mean_df['전체승하차'] * 100).round(2)

In [161]:
# seoul_mean_df.to_csv('subway_mean.csv', index=False, encoding='utf-8-sig')

In [162]:
# 지하철역 칼럼에서 정규식() 지우기.
seoul_mean_df['호선명'] = seoul_mean_df['호선명'].str.replace(r'\(.*?\)', '', regex=True).str.strip()

print(seoul_mean_df['호선명'].unique())

['1호선' '2호선' '3호선' '4호선' '5호선' '6호선' '7호선' '8호선' '9호선']

/var/folders/rx/ylxcpmnn5hz6xwbkxhnfnxfm0000gn/T/ipykernel_7953/1498199914.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_mean_df['호선명'] = seoul_mean_df['호선명'].str.replace(r'\(.*?\)', '', regex=True).str.strip()

In [163]:
seoul_mean_df

,호선명,지하철역,총승차인원,무임승차인원,총하차인원,무임하차인원,전체승하차,무임승하차,무임승하차비중
0,1호선,동대문,363678.0,125523.0,356249.0,125026.0,719927.0,250549.0,34.80
1,1호선,동묘앞,308894.0,157888.0,316892.0,159511.0,625786.0,317399.0,50.72
2,1호선,서울역,1794960.0,229681.0,1701907.0,217787.0,3496867.0,447468.0,12.80
3,1호선,시청,762366.0,107582.0,766076.0,105764.0,1528442.0,213346.0,13.96
4,1호선,신설동,411861.0,120797.0,397175.0,117111.0,809036.0,237908.0,29.41
...,...,...,...,...,...,...,...,...,...
308,9호선,양천향교,289659.0,49752.0,294136.0,49308.0,583795.0,99060.0,16.97
309,9호선,여의도,840341.0,56004.0,804546.0,51738.0,1644887.0,107742.0,6.55
310,9호선,염창,514529.0,80870.0,492565.0,78794.0,1007094.0,159664.0,15.85
311,9호선,증미,219073.0,38743.0,210572.0,38823.0,429645.0,77566.0,18.05
312,9호선,흑석(중앙대입구),274749.0,60214.0,279485.0,60496.0,554234.0,120710.0,21.78

In [164]:
# seoul_mean_df.to_csv('subway_mean.csv', index=False, encoding='utf-8-sig')

In [165]:
# 상봉역이 2023년 → 상봉(시외버스터미널) (7호선) 2024년부터 → 상봉 (7호선) 으로 되어있어 2개여서  확인용
print(line_1_9_df[line_1_9_df['지하철역'].str.contains('상봉')][['호선명', '지하철역', '사용월']].sort_values('사용월'))

       호선명 지하철역     사용월
7000   7호선   상봉  202301
6407   7호선   상봉  202302
5766   7호선   상봉  202303
5172   7호선   상봉  202304
4559   7호선   상봉  202305
3952   7호선   상봉  202306
3313   7호선   상봉  202307
2716   7호선   상봉  202308
2082   7호선   상봉  202309
1476   7호선   상봉  202310
852    7호선   상봉  202311
247    7호선   상봉  202312
14461  7호선   상봉  202401
13810  7호선   상봉  202402
13200  7호선   상봉  202403
12575  7호선   상봉  202404
11959  7호선   상봉  202405
11358  7호선   상봉  202406
10716  7호선   상봉  202407
10096  7호선   상봉  202408
9493   7호선   상봉  202409
8863   7호선   상봉  202410
8253   7호선   상봉  202411
7612   7호선   상봉  202412
21915  7호선   상봉  202501
21293  7호선   상봉  202502
20676  7호선   상봉  202503
20032  7호선   상봉  202504
19413  7호선   상봉  202505
18795  7호선   상봉  202506
18188  7호선   상봉  202507
17549  7호선   상봉  202508
16943  7호선   상봉  202509
16304  7호선   상봉  202510
15682  7호선   상봉  202511
15079  7호선   상봉  202512

In [166]:
# 중복된역(환승역)나누기
transfer_stations = seoul_mean_df[seoul_mean_df['지하철역'].duplicated(keep=False)]['지하철역'].unique()

In [167]:
# 환승역
transfer_df = seoul_mean_df[seoul_mean_df['지하철역'].isin(transfer_stations)]
transfer_df

,호선명,지하철역,총승차인원,무임승차인원,총하차인원,무임하차인원,전체승하차,무임승하차,무임승하차비중
0,1호선,동대문,363678.0,125523.0,356249.0,125026.0,719927.0,250549.0,34.80
1,1호선,동묘앞,308894.0,157888.0,316892.0,159511.0,625786.0,317399.0,50.72
2,1호선,서울역,1794960.0,229681.0,1701907.0,217787.0,3496867.0,447468.0,12.80
3,1호선,시청,762366.0,107582.0,766076.0,105764.0,1528442.0,213346.0,13.96
4,1호선,신설동,411861.0,120797.0,397175.0,117111.0,809036.0,237908.0,29.41
...,...,...,...,...,...,...,...,...,...
290,9호선,고속터미널,469482.0,72545.0,644629.0,86716.0,1114111.0,159261.0,14.29
294,9호선,김포공항,207590.0,20139.0,322049.0,27599.0,529639.0,47738.0,9.01
297,9호선,당산,557799.0,73618.0,548013.0,68347.0,1105812.0,141965.0,12.84
298,9호선,동작(현충원),60162.0,15160.0,52065.0,13729.0,112227.0,28889.0,25.74
309,9호선,여의도,840341.0,56004.0,804546.0,51738.0,1644887.0,107742.0,6.55

In [168]:
# 비환승역
non_transfer_df = seoul_mean_df[~seoul_mean_df['지하철역'].isin(transfer_stations)]
non_transfer_df

,호선명,지하철역,총승차인원,무임승차인원,총하차인원,무임하차인원,전체승하차,무임승하차,무임승하차비중
5,1호선,제기동,501317.0,269661.0,511782.0,290055.0,1013099.0,559716.0,55.25
6,1호선,종각,1112527.0,151760.0,1083408.0,140929.0,2195935.0,292689.0,13.33
8,1호선,종로5가,712905.0,247967.0,697910.0,240352.0,1410815.0,488319.0,34.61
9,1호선,청량리(서울시립대입구),662997.0,280334.0,656727.0,281655.0,1319724.0,561989.0,42.58
10,2호선,강남,2302759.0,161221.0,2246564.0,140970.0,4549323.0,302191.0,6.64
...,...,...,...,...,...,...,...,...,...
307,9호선,신방화,202870.0,49967.0,198595.0,50170.0,401465.0,100137.0,24.94
308,9호선,양천향교,289659.0,49752.0,294136.0,49308.0,583795.0,99060.0,16.97
310,9호선,염창,514529.0,80870.0,492565.0,78794.0,1007094.0,159664.0,15.85
311,9호선,증미,219073.0,38743.0,210572.0,38823.0,429645.0,77566.0,18.05
312,9호선,흑석(중앙대입구),274749.0,60214.0,279485.0,60496.0,554234.0,120710.0,21.78

In [169]:
# 환승역 합치기.
transfer_grouped = transfer_df.groupby('지하철역')[['총승차인원', '무임승차인원', '총하차인원', '무임하차인원', '전체승하차', '무임승하차']].sum().round(0).reset_index()

# 비중 재계산
transfer_grouped['무임승하차비중'] = (transfer_grouped['무임승하차'] / transfer_grouped['전체승하차'] * 100).round(2)

# 역명에 (환승) 태그 추가
transfer_grouped['지하철역'] = transfer_grouped['지하철역'] + '(환승)'

print(transfer_grouped)
transfer_grouped.head()

                  지하철역      총승차인원    무임승차인원      총하차인원    무임하차인원      전체승하차  \
0             가락시장(환승)   499142.0  149493.0   517546.0  148748.0  1016688.0
1             건대입구(환승)  1514545.0  160449.0  1584989.0  158811.0  3099534.0
2            고속터미널(환승)  2526704.0  378399.0  2523557.0  369982.0  5050261.0
3               공덕(환승)   948702.0  133694.0   949611.0  125787.0  1898313.0
4       교대(법원.검찰청)(환승)  1330717.0  237048.0  1305183.0  227756.0  2635900.0
5           군자(능동)(환승)   785877.0  132473.0   726097.0  123065.0  1511974.0
6             김포공항(환승)   530431.0   70323.0   557489.0   71426.0  1087920.0
7               노원(환승)  1278860.0  265098.0  1389731.0  265470.0  2668591.0
8               당산(환승)  1086434.0  134157.0  1153742.0  134381.0  2240176.0
9         대림(구로구청)(환승)   989147.0  182965.0  1006134.0  186565.0  1995281.0
10             동대문(환승)   932876.0  279178.0   940024.0  274204.0  1872900.0
11  동대문역사문화공원(DDP)(환승)  1099733.0  133930.0  1106872.0  132983.0  2206605.0
12             동묘앞(환승)   570181.0  229441.0   579997.0  226056.0  1150178.0
13         동작(현충원)(환승)   109569.0   29737.0   104756.0   28535.0   214325.0
14              불광(환승)   628909.0  190903.0   657152.0  198424.0  1286061.0
15              사당(환승)  1988942.0  323350.0  2017546.0  317669.0  4006488.0
16             삼각지(환승)   408593.0   45762.0   409492.0   43629.0   818085.0
17      삼각지(전쟁기념관)(환승)   452326.0   46910.0   462092.0   44925.0   914418.0
18             서울역(환승)  2155185.0  271561.0  2358354.0  275553.0  4513539.0
19              시청(환승)  1504288.0  170657.0  1458576.0  162682.0  2962864.0
20              신당(환승)   687585.0  132734.0   712506.0  133571.0  1400091.0
21             신설동(환승)   525201.0  154123.0   508111.0  152088.0  1033312.0
22              약수(환승)   485940.0  106219.0   473228.0  100590.0   959168.0
23             여의도(환승)  1643461.0  114204.0  1652659.0  107101.0  3296120.0
24             연신내(환승)  1036393.0  264167.0   985977.0  255205.0  2022370.0
25           영등포구청(환승)   758286.0  126191.0   775157.0  124777.0  1533443.0
26              오금(환승)   291808.0   56755.0   273271.0   54128.0   565079.0
27       왕십리(성동구청)(환승)   602261.0   79888.0   577607.0   75030.0  1179868.0
28           을지로3가(환승)  1051252.0  125034.0  1045244.0  121016.0  2096496.0
29           을지로4가(환승)   589848.0  119702.0   592977.0  118251.0  1182825.0
30        잠실(송파구청)(환승)  2898750.0  309717.0  2944462.0  298290.0  5843212.0
31            종로3가(환승)  1557687.0  458436.0  1539083.0  445192.0  3096770.0
32        천호(풍납토성)(환승)  1055612.0  253203.0  1108370.0  252351.0  2163982.0
33              청구(환승)   219899.0   44565.0   211920.0   42532.0   431819.0
34             충무로(환승)   867520.0  119883.0   893846.0  121889.0  1761366.0
35      충정로(경기대입구)(환승)   417744.0   63616.0   436275.0   64124.0   854019.0
36            태릉입구(환승)   438855.0   87568.0   443702.0   85169.0   882557.0
37              합정(환승)  1379809.0  113748.0  1461301.0  111461.0  2841110.0

       무임승하차  무임승하차비중
0   298241.0    29.33
1   319260.0    10.30
2   748381.0    14.82
3   259481.0    13.67
4   464804.0    17.63
5   255538.0    16.90
6   141749.0    13.03
7   530568.0    19.88
8   268538.0    11.99
9   369530.0    18.52
10  553382.0    29.55
11  266913.0    12.10
12  455497.0    39.60
13   58272.0    27.19
14  389327.0    30.27
15  641019.0    16.00
16   89391.0    10.93
17   91835.0    10.04
18  547114.0    12.12
19  333339.0    11.25
20  266305.0    19.02
21  306211.0    29.63
22  206809.0    21.56
23  221305.0     6.71
24  519372.0    25.68
25  250968.0    16.37
26  110883.0    19.62
27  154918.0    13.13
28  246050.0    11.74
29  237953.0    20.12
30  608007.0    10.41
31  903628.0    29.18
32  505554.0    23.36
33   87097.0    20.17
34  241772.0    13.73
35  127740.0    14.96
36  172737.0    19.57
37  225209.0     7.93

,지하철역,총승차인원,무임승차인원,총하차인원,무임하차인원,전체승하차,무임승하차,무임승하차비중
0,가락시장(환승),499142.0,149493.0,517546.0,148748.0,1016688.0,298241.0,29.33
1,건대입구(환승),1514545.0,160449.0,1584989.0,158811.0,3099534.0,319260.0,10.30
2,고속터미널(환승),2526704.0,378399.0,2523557.0,369982.0,5050261.0,748381.0,14.82
3,공덕(환승),948702.0,133694.0,949611.0,125787.0,1898313.0,259481.0,13.67
4,교대(법원.검찰청)(환승),1330717.0,237048.0,1305183.0,227756.0,2635900.0,464804.0,17.63

In [170]:
transfer_grouped['호선명'] = '환승'

In [171]:
df_all = pd.concat([non_transfer_df, transfer_grouped], ignore_index=True)
df_all

,호선명,지하철역,총승차인원,무임승차인원,총하차인원,무임하차인원,전체승하차,무임승하차,무임승하차비중
0,1호선,제기동,501317.0,269661.0,511782.0,290055.0,1013099.0,559716.0,55.25
1,1호선,종각,1112527.0,151760.0,1083408.0,140929.0,2195935.0,292689.0,13.33
2,1호선,종로5가,712905.0,247967.0,697910.0,240352.0,1410815.0,488319.0,34.61
3,1호선,청량리(서울시립대입구),662997.0,280334.0,656727.0,281655.0,1319724.0,561989.0,42.58
4,2호선,강남,2302759.0,161221.0,2246564.0,140970.0,4549323.0,302191.0,6.64
...,...,...,...,...,...,...,...,...,...
245,환승,청구(환승),219899.0,44565.0,211920.0,42532.0,431819.0,87097.0,20.17
246,환승,충무로(환승),867520.0,119883.0,893846.0,121889.0,1761366.0,241772.0,13.73
247,환승,충정로(경기대입구)(환승),417744.0,63616.0,436275.0,64124.0,854019.0,127740.0,14.96
248,환승,태릉입구(환승),438855.0,87568.0,443702.0,85169.0,882557.0,172737.0,19.57
249,환승,합정(환승),1379809.0,113748.0,1461301.0,111461.0,2841110.0,225209.0,7.93

In [172]:
df_all['호선명'] = df_all['호선명'].str.replace('호선', '').str.strip()

print(df_all['호선명'].unique())

['1' '2' '3' '4' '5' '6' '7' '8' '9' '환승']

In [173]:
df_all['지하철역'] = df_all['지하철역'].str.replace(r'\(.*\)', '', regex=True).str.strip()

In [174]:
df_all['지하철역']

0       제기동
1        종각
2      종로5가
3       청량리
4        강남
       ...
245      청구
246     충무로
247     충정로
248    태릉입구
249      합정
Name: 지하철역, Length: 250, dtype: object

In [175]:
df_all

,호선명,지하철역,총승차인원,무임승차인원,총하차인원,무임하차인원,전체승하차,무임승하차,무임승하차비중
0,1,제기동,501317.0,269661.0,511782.0,290055.0,1013099.0,559716.0,55.25
1,1,종각,1112527.0,151760.0,1083408.0,140929.0,2195935.0,292689.0,13.33
2,1,종로5가,712905.0,247967.0,697910.0,240352.0,1410815.0,488319.0,34.61
3,1,청량리,662997.0,280334.0,656727.0,281655.0,1319724.0,561989.0,42.58
4,2,강남,2302759.0,161221.0,2246564.0,140970.0,4549323.0,302191.0,6.64
...,...,...,...,...,...,...,...,...,...
245,환승,청구,219899.0,44565.0,211920.0,42532.0,431819.0,87097.0,20.17
246,환승,충무로,867520.0,119883.0,893846.0,121889.0,1761366.0,241772.0,13.73
247,환승,충정로,417744.0,63616.0,436275.0,64124.0,854019.0,127740.0,14.96
248,환승,태릉입구,438855.0,87568.0,443702.0,85169.0,882557.0,172737.0,19.57
249,환승,합정,1379809.0,113748.0,1461301.0,111461.0,2841110.0,225209.0,7.93

In [176]:
# 주요 환승역 매핑 정보를 구성
transfer_mapping = {
    '가락시장': '3,8', '건대입구': '2,7', '고속터미널': '3,7,9', '공덕': '5,6',
    '교대': '2,3', '군자': '5,7', '김포공항': '5,9', '노원': '4,7',
    '당산': '2,9', '대림': '2,7', '동대문': '1,4', '동대문역사문화공원': '2,4,5',
    '동묘앞': '1,6', '동작': '4,9', '불광': '3,6', '사당': '2,4',
    '삼각지': '4,6', '서울역': '1,4', '시청': '1,2', '신당': '2,6',
    '신설동': '1,2', '약수': '3,6', '여의도': '5,9', '연신내': '3,6',
    '영등포구청': '2,5', '오금': '3,5', '왕십리': '2,5', '을지로3가': '2,3',
    '을지로4가': '2,5', '잠실': '2,8', '종로3가': '1,3,5', '천호': '5,8',
    '청구': '5,6', '충무로': '3,4', '충정로': '2,5', '태릉입구': '6,7', '합정': '2,6'
}

# '호선명'이 '환승'인 경우에만 딕셔너리에서 역명을 찾아 호선 정보로 교체
def update_line_name(row):
    if row['호선명'] == '환승':
        return transfer_mapping.get(row['지하철역'], row['호선명'])
    return row['호선명']

In [177]:
# apply 함수를 사용해 한 번에 적용
df_all['호선명'] = df_all.apply(update_line_name, axis=1)

In [178]:
df_all.tail()

,호선명,지하철역,총승차인원,무임승차인원,총하차인원,무임하차인원,전체승하차,무임승하차,무임승하차비중
245,"5,6",청구,219899.0,44565.0,211920.0,42532.0,431819.0,87097.0,20.17
246,"3,4",충무로,867520.0,119883.0,893846.0,121889.0,1761366.0,241772.0,13.73
247,"2,5",충정로,417744.0,63616.0,436275.0,64124.0,854019.0,127740.0,14.96
248,"6,7",태릉입구,438855.0,87568.0,443702.0,85169.0,882557.0,172737.0,19.57
249,"2,6",합정,1379809.0,113748.0,1461301.0,111461.0,2841110.0,225209.0,7.93

In [179]:
df_all.to_csv('subway_final.csv', index=False, encoding='utf-8-sig')